//
// Created by DELL on 19/01/2026.
//

#ifndef BANKINGSYSTEM_MANAGERCONTROLLER_HPP
#define BANKINGSYSTEM_MANAGERCONTROLLER_HPP


class ManagerController {
};


#endif //BANKINGSYSTEM_MANAGERCONTROLLER_HPP